modules:
  - apps/android-app
  - apps/ios-app
  - apps/shared
  - domain
  - navigation
  - core/base
  - data/database
  - data/datastore
  - data/network
  - data/repository
  - data/store
  - presenter/home
  - presenter/cardsetchooser
  - theme
